const api=window.REPOGUARD_API_BASE.replace(/\/$/,""); const id=new URLSearchParams(location.search).get("id"); const box=document.getElementById("report");
const el=(tag,text,cls)=>{const x=document.createElement(tag); if(cls)x.className=cls; x.textContent=text; return x;};
function findingCard(f){const d=document.createElement("details"); d.className="finding"; d.append(el("summary",f.severity.toUpperCase()+" — "+f.file+":"+f.line+" — "+f.rule)); d.append(el("div","Snippet: "+f.snippet),el("div","Why it matters: "+f.explanation),el("div","Scanner: "+f.source)); return d;}
async function load(){if(!id){box.append(el("p","Missing scan id","error"));return;} try{const r=await fetch(api+"/report?id="+encodeURIComponent(id),{cache:"no-store"}); if(r.status===202){box.append(el("h1","Scan queued or still running")); setTimeout(()=>location.reload(),3000); return;} const d=await r.json(); if(!r.ok) throw new Error(d.error||"report unavailable"); render(d);}catch(e){box.append(el("p",String(e.message||e),"error")); setTimeout(()=>location.reload(),5000);}}
function render(d){
 const h=document.createElement("section"); h.className="card verdict "+String(d.verdict||"").toLowerCase(); h.append(el("h1",d.verdict),el("p",(d.files_analyzed||0)+" of "+(d.files_total||0)+" files analyzed"),el("p","Commit: "+d.commit_sha),el("p","Mode: "+d.mode),el("p","Scanned: "+d.scanned_at)); if(d.outdated)h.append(el("p","OUTDATED: current HEAD is "+(d.current_head_sha||"not available"),"warning")); box.append(h);
 const btn=document.createElement("button"); btn.textContent="Export JSON"; btn.onclick=()=>{const blob=new Blob([JSON.stringify(d,null,2)],{type:"application/json"}); const a=document.createElement("a"); a.href=URL.createObjectURL(blob); a.download="repoguard-"+(d.scan_id||id)+".json"; a.click(); URL.revokeObjectURL(a.href);}; box.append(btn);
 const checks=document.createElement("section"); checks.className="card"; checks.append(el("h2","Checks run")); (d.checks||[]).forEach(c=>checks.append(el("p",(c.status||"")+" : "+c.check+(c.detail?" — "+c.detail:"")))); box.append(checks);
 const reasons=document.createElement("section"); reasons.className="card"; reasons.append(el("h2","Rejection reasons")); if(!(d.rejection_reasons||[]).length) reasons.append(el("p","None")); (d.rejection_reasons||[]).forEach(x=>reasons.append(el("p",x.file+": "+x.reason))); box.append(reasons);
 const fs=document.createElement("section"); fs.className="card"; fs.append(el("h2","Findings")); (d.findings||[]).forEach(f=>fs.append(findingCard(f))); if(!(d.findings||[]).length) fs.append(el("p","No findings at or above the configured severity threshold.")); box.append(fs);
 const inv=document.createElement("section"); inv.className="card"; inv.append(el("h2","File inventory")); (d.file_results||[]).forEach(f=>{const p=document.createElement("p"); p.append(el("strong",f.status+" — "),el("span",f.path+" ("+f.file_type+", "+f.size+" bytes, SHA-256 "+f.sha256+")")); inv.append(p);}); box.append(inv);
}
load();
